Importing the Dependencies

In [5]:
import pandas as pd
import censusdata
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.precision', 2)

Checking all the variables and profile table in Census

In [6]:
#Working with the profile tables of Census 
censusdata.search('acs1', 2018, 'label', 'age', tabletype='profile')[-25:]

[('DP05_0023PE',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Percent Estimate!!SEX AND AGE!!Total population!!62 years and over'),
 ('DP05_0024E',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Estimate!!SEX AND AGE!!Total population!!65 years and over'),
 ('DP05_0024PE',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Percent Estimate!!SEX AND AGE!!Total population!!65 years and over'),
 ('DP05_0025E',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Estimate!!SEX AND AGE!!Total population!!18 years and over'),
 ('DP05_0025PE',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Percent Estimate!!SEX AND AGE!!Total population!!18 years and over'),
 ('DP05_0026E',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male'),
 ('DP05_0026PE',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Percent Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male'),
 ('DP05_0027E',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female'),
 ('DP05_0027PE',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Percent Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female'),
 ('DP05_0028E',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females)'),
 ('DP05_0028PE',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Percent Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females)'),
 ('DP05_0029E',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Estimate!!SEX AND AGE!!Total population!!65 years and over'),
 ('DP05_0029PE',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Percent Estimate!!SEX AND AGE!!Total population!!65 years and over'),
 ('DP05_0030E',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male'),
 ('DP05_0030PE',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Percent Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male'),
 ('DP05_0031E',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female'),
 ('DP05_0031PE',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Percent Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female'),
 ('DP05_0032E',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)'),
 ('DP05_0032PE',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Percent Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)'),
 ('DP05_0087E',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population'),
 ('DP05_0087PE',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Percent Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population'),
 ('DP05_0088E',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male'),
 ('DP05_0088PE',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Percent Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male'),
 ('DP05_0089E',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female'),
 ('DP05_0089PE',
  'ACS DEMOGRAPHIC AND HOUSING ESTIMATES',
  'Percent Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female')]

In [7]:
censusdata.printtable(censusdata.censustable('acs1', 2018, 'DP05'))

Variable     | Table                          | Label                                                    | Type
-------------------------------------------------------------------------------------------------------------------
DP05_0001E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate SEX AND AGE Total population              | int
DP05_0001PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate SEX AND AGE Total population      | int
DP05_0002E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Male      | int
DP05_0002PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population M | float
DP05_0003E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Female    | int
DP05_0003PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population F | float
DP05_0004E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Sex ratio | float
DP05_0004PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population S | int
DP05_0005E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Under 5 y | int
DP05_0005PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population U | float
DP05_0006E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 5 to 9 ye | int
DP05_0006PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 5 | float
DP05_0007E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 10 to 14  | int
DP05_0007PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | float
DP05_0008E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 15 to 19  | int
DP05_0008PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | float
DP05_0009E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 20 to 24  | int
DP05_0009PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 2 | float
DP05_0010E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 25 to 34  | int
DP05_0010PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 2 | float
DP05_0011E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 35 to 44  | int
DP05_0011PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 3 | float
DP05_0012E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 45 to 54  | int
DP05_0012PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 4 | float
DP05_0013E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 55 to 59  | int
DP05_0013PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 5 | float
DP05_0014E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 60 to 64  | int
DP05_0014PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | float
DP05_0015E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 65 to 74  | int
DP05_0015PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | float
DP05_0016E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 75 to 84  | int
DP05_0016PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 7 | float
DP05_0017E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 85 years  | int
DP05_0017PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 8 | float
DP05_0018E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Median ag | float
DP05_0018PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population M | int
DP05_0019E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Under 18  | int
DP05_0019PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population U | float
DP05_0020E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 16 years  | int
DP05_0020PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | float
DP05_0021E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 18 years  | int
DP05_0021PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | float
DP05_0022E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 21 years  | int
DP05_0022PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 2 | float
DP05_0023E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 62 years  | int
DP05_0023PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | float
DP05_0024E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 65 years  | int
DP05_0024PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | float
DP05_0025E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 18 years  | int
DP05_0025PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | int
DP05_0026E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 18 yea | int
DP05_0026PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | float
DP05_0027E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 18 yea | int
DP05_0027PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | float
DP05_0028E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 18 yea | float
DP05_0028PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | int
DP05_0029E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 65 years  | int
DP05_0029PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | int
DP05_0030E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 65 yea | int
DP05_0030PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | float
DP05_0031E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 65 yea | int
DP05_0031PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | float
DP05_0032E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 65 yea | float
DP05_0032PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | int
DP05_0033E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate RACE Total population                     | int
DP05_0033PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate RACE Total population             | int
DP05_0034E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate RACE Total population One race         | int
DP05_0034PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate RACE Total population One race | float
DP05_0035E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate RACE Total population Two or more race | int
DP05_0035PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate RACE Total population Two or m | float
DP05_0036E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate RACE Total population One race         | int
DP05_0036PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate RACE Total population One race | float
DP05_0037E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Whit | int
DP05_0037PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0038E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Blac | int
DP05_0038PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0039E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Amer | int
DP05_0039PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0040E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0040PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0041E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0041PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0042E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0042PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0043E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0043PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0044E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Asia | int
DP05_0044PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0045E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0045PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0046E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0046PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0047E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0047PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0048E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0048PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0049E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0049PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0050E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0050PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0051E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0051PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0052E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Nati | int
DP05_0052PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0053E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race N | int
DP05_0053PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0054E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race N | int
DP05_0054PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0055E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race N | int
DP05_0055PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0056E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race N | int
DP05_0056PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0057E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Some | int
DP05_0057PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0058E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate RACE Total population Two or more race | int
DP05_0058PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate RACE Total population Two or m | float
DP05_0059E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population Two or more r | int
DP05_0059PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population Two o | float
DP05_0060E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population Two or more r | int
DP05_0060PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population Two o | float
DP05_0061E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population Two or more r | int
DP05_0061PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population Two o | float
DP05_0062E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population Two or more r | int
DP05_0062PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population Two o | float
DP05_0063E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate Race alone or in combination with one or  | int
DP05_0063PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate Race alone or in combination with | int
DP05_0064E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0064PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0065E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0065PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0066E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0066PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0067E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0067PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0068E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0068PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0069E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0069PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0070E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate HISPANIC OR LATINO AND RACE Total populat | int
DP05_0070PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate HISPANIC OR LATINO AND RACE Total | int
DP05_0071E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate HISPANIC OR LATINO AND RACE Total popu | int
DP05_0071PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE To | float
DP05_0072E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0072PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0073E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0073PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0074E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0074PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0075E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0075PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0076E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate HISPANIC OR LATINO AND RACE Total popu | int
DP05_0076PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE To | float
DP05_0077E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0077PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0078E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0078PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0079E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0079PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0080E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0080PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0081E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0081PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0082E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0082PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0083E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0083PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0084E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Tota | int
DP05_0084PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate HISPANIC OR LATINO AND R | float
DP05_0085E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Tota | int
DP05_0085PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate HISPANIC OR LATINO AND R | float
DP05_0086E   | ACS DEMOGRAPHIC AND HOUSING ES | !! Estimate Total housing units                          | int
DP05_0086PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! Percent Estimate Total housing units                  | int
DP05_0087E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate CITIZEN, VOTING AGE POPULATION Citizen, 1 | int
DP05_0087PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate CITIZEN, VOTING AGE POPULATION Ci | int
DP05_0088E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate CITIZEN, VOTING AGE POPULATION Citizen | int
DP05_0088PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate CITIZEN, VOTING AGE POPULATION | float

In [8]:
#/creating the dataframes 
county65plus = censusdata.download('acs1', 2018, censusdata.censusgeo([('county', '*')]),
                                   ['DP05_0001E', 'DP05_0014PE', 'DP05_0015PE', 'DP05_0016PE',],
                                   tabletype='profile')
county65plus.describe()

       DP05_0001E  DP05_0014PE  DP05_0015PE  DP05_0016PE
count    8.38e+02       838.00       838.00       838.00
mean     3.34e+05         6.52         9.80         4.98
std      5.87e+05         1.09         2.31         1.54
min      6.26e+04         3.20         4.60         2.00
25%      9.53e+04         5.70         8.40         4.00
50%      1.59e+05         6.50         9.50         4.80
75%      3.31e+05         7.20        10.90         5.60
max      1.01e+07        10.40        32.70        20.30

In [9]:
county65plus['percent_65plus'] = (county65plus['DP05_0014PE'] + county65plus['DP05_0015PE']
                                  + county65plus['DP05_0016PE'])
county65plus = county65plus[['DP05_0001E', 'percent_65plus']]
county65plus = county65plus.rename(columns={'DP05_0001E': 'population_size'})
county65plus.sort_values('percent_65plus', ascending=False, inplace=True)
county65plus.head(30)

                                                    population_size  percent_65plus
Sumter County, Florida: Summary level: 050, sta...           128754            62.1
Charlotte County, Florida: Summary level: 050, ...           184998            43.8
Citrus County, Florida: Summary level: 050, sta...           147929            41.6
Brunswick County, North Carolina: Summary level...           136744            40.4
Sarasota County, Florida: Summary level: 050, s...           426718            39.2
Indian River County, Florida: Summary level: 05...           157413            38.3
Yavapai County, Arizona: Summary level: 050, st...           231993            37.9
Mohave County, Arizona: Summary level: 050, sta...           209550            36.7
Highlands County, Florida: Summary level: 050, ...           105424            36.6
Barnstable County, Massachusetts: Summary level...           213413            35.9
Collier County, Florida: Summary level: 050, st...           378488            34.6
Sussex County, Delaware: Summary level: 050, st...           229286            34.5
Flagler County, Florida: Summary level: 050, st...           112067            34.2
Martin County, Florida: Summary level: 050, sta...           160912            34.0
Nevada County, California: Summary level: 050, ...            99696            33.5
Clallam County, Washington: Summary level: 050,...            76737            33.1
Marion County, Florida: Summary level: 050, sta...           359977            32.5
Cape May County, New Jersey: Summary level: 050...            92560            32.1
Josephine County, Oregon: Summary level: 050, s...            87393            32.1
Hernando County, Florida: Summary level: 050, s...           190865            32.0
Lee County, Florida: Summary level: 050, state:...           754610            32.0
Beaufort County, South Carolina: Summary level:...           188715            31.5
Douglas County, Oregon: Summary level: 050, sta...           110283            31.4
Lake County, Florida: Summary level: 050, state...           356495            31.3
Manatee County, Florida: Summary level: 050, st...           394855            31.2
Carteret County, North Carolina: Summary level:...            69524            31.1
Horry County, South Carolina: Summary level: 05...           344147            30.7
Santa Fe County, New Mexico: Summary level: 050...           150056            30.5
James City County, Virginia: Summary level: 050...            76397            30.5
Island County, Washington: Summary level: 050, ...            84460            30.4

In [10]:
censusdata.printtable(censusdata.censustable('acs1', 2018, 'DP05'))

Variable     | Table                          | Label                                                    | Type
-------------------------------------------------------------------------------------------------------------------
DP05_0001E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate SEX AND AGE Total population              | int
DP05_0001PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate SEX AND AGE Total population      | int
DP05_0002E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Male      | int
DP05_0002PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population M | float
DP05_0003E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Female    | int
DP05_0003PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population F | float
DP05_0004E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Sex ratio | float
DP05_0004PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population S | int
DP05_0005E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Under 5 y | int
DP05_0005PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population U | float
DP05_0006E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 5 to 9 ye | int
DP05_0006PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 5 | float
DP05_0007E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 10 to 14  | int
DP05_0007PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | float
DP05_0008E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 15 to 19  | int
DP05_0008PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | float
DP05_0009E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 20 to 24  | int
DP05_0009PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 2 | float
DP05_0010E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 25 to 34  | int
DP05_0010PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 2 | float
DP05_0011E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 35 to 44  | int
DP05_0011PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 3 | float
DP05_0012E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 45 to 54  | int
DP05_0012PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 4 | float
DP05_0013E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 55 to 59  | int
DP05_0013PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 5 | float
DP05_0014E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 60 to 64  | int
DP05_0014PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | float
DP05_0015E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 65 to 74  | int
DP05_0015PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | float
DP05_0016E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 75 to 84  | int
DP05_0016PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 7 | float
DP05_0017E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 85 years  | int
DP05_0017PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 8 | float
DP05_0018E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Median ag | float
DP05_0018PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population M | int
DP05_0019E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Under 18  | int
DP05_0019PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population U | float
DP05_0020E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 16 years  | int
DP05_0020PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | float
DP05_0021E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 18 years  | int
DP05_0021PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | float
DP05_0022E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 21 years  | int
DP05_0022PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 2 | float
DP05_0023E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 62 years  | int
DP05_0023PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | float
DP05_0024E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 65 years  | int
DP05_0024PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | float
DP05_0025E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 18 years  | int
DP05_0025PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | int
DP05_0026E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 18 yea | int
DP05_0026PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | float
DP05_0027E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 18 yea | int
DP05_0027PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | float
DP05_0028E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 18 yea | float
DP05_0028PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | int
DP05_0029E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 65 years  | int
DP05_0029PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | int
DP05_0030E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 65 yea | int
DP05_0030PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | float
DP05_0031E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 65 yea | int
DP05_0031PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | float
DP05_0032E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 65 yea | float
DP05_0032PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | int
DP05_0033E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate RACE Total population                     | int
DP05_0033PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate RACE Total population             | int
DP05_0034E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate RACE Total population One race         | int
DP05_0034PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate RACE Total population One race | float
DP05_0035E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate RACE Total population Two or more race | int
DP05_0035PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate RACE Total population Two or m | float
DP05_0036E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate RACE Total population One race         | int
DP05_0036PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate RACE Total population One race | float
DP05_0037E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Whit | int
DP05_0037PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0038E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Blac | int
DP05_0038PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0039E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Amer | int
DP05_0039PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0040E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0040PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0041E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0041PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0042E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0042PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0043E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0043PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0044E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Asia | int
DP05_0044PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0045E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0045PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0046E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0046PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0047E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0047PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0048E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0048PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0049E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0049PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0050E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0050PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0051E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0051PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0052E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Nati | int
DP05_0052PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0053E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race N | int
DP05_0053PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0054E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race N | int
DP05_0054PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0055E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race N | int
DP05_0055PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0056E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race N | int
DP05_0056PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0057E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Some | int
DP05_0057PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0058E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate RACE Total population Two or more race | int
DP05_0058PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate RACE Total population Two or m | float
DP05_0059E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population Two or more r | int
DP05_0059PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population Two o | float
DP05_0060E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population Two or more r | int
DP05_0060PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population Two o | float
DP05_0061E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population Two or more r | int
DP05_0061PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population Two o | float
DP05_0062E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population Two or more r | int
DP05_0062PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population Two o | float
DP05_0063E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate Race alone or in combination with one or  | int
DP05_0063PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate Race alone or in combination with | int
DP05_0064E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0064PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0065E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0065PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0066E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0066PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0067E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0067PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0068E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0068PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0069E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0069PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0070E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate HISPANIC OR LATINO AND RACE Total populat | int
DP05_0070PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate HISPANIC OR LATINO AND RACE Total | int
DP05_0071E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate HISPANIC OR LATINO AND RACE Total popu | int
DP05_0071PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE To | float
DP05_0072E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0072PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0073E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0073PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0074E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0074PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0075E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0075PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0076E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate HISPANIC OR LATINO AND RACE Total popu | int
DP05_0076PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE To | float
DP05_0077E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0077PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0078E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0078PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0079E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0079PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0080E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0080PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0081E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0081PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0082E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0082PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0083E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0083PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0084E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Tota | int
DP05_0084PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate HISPANIC OR LATINO AND R | float
DP05_0085E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Tota | int
DP05_0085PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate HISPANIC OR LATINO AND R | float
DP05_0086E   | ACS DEMOGRAPHIC AND HOUSING ES | !! Estimate Total housing units                          | int
DP05_0086PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! Percent Estimate Total housing units                  | int
DP05_0087E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate CITIZEN, VOTING AGE POPULATION Citizen, 1 | int
DP05_0087PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate CITIZEN, VOTING AGE POPULATION Ci | int
DP05_0088E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate CITIZEN, VOTING AGE POPULATION Citizen | int
DP05_0088PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate CITIZEN, VOTING AGE POPULATION | float

In [11]:
#Help to download the data 
county2035plus = censusdata.download('acs1', 2018, censusdata.censusgeo([('county', '*')]),
                                   ['DP05_0001E', 'DP05_0009PE', 'DP05_0010PE'],
                                   tabletype='profile')
county2035plus.describe()

       DP05_0001E  DP05_0009PE  DP05_0010PE
count    8.38e+02       838.00       838.00
mean     3.34e+05         6.95        13.08
std      5.87e+05         2.61         2.17
min      6.26e+04         1.70         5.70
25%      9.53e+04         5.60        11.80
50%      1.59e+05         6.20        12.80
75%      3.31e+05         7.10        14.10
max      1.01e+07        25.90        23.70

In [12]:
county2035plus['percent_2035plus'] = (county2035plus['DP05_0009PE'] + county2035plus['DP05_0010PE'])
county2035plus =county2035plus[['DP05_0001E', 'percent_2035plus']]
county2035plus = county2035plus.rename(columns={'DP05_0001E': 'population_size'})
county2035plus.sort_values('percent_2035plus', ascending=False, inplace=True)
county2035plus.head(30)

                                                    population_size  percent_2035plus
Riley County, Kansas: Summary level: 050, state...            73703              43.5
Brazos County, Texas: Summary level: 050, state...           226758              34.8
Story County, Iowa: Summary level: 050, state:1...            98105              34.5
Onslow County, North Carolina: Summary level: 0...           197683              34.4
Clarke County, Georgia: Summary level: 050, sta...           127330              33.9
Suffolk County, Massachusetts: Summary level: 0...           807252              33.0
Montgomery County, Virginia: Summary level: 050...            98985              32.9
Lynchburg city, Virginia: Summary level: 050, s...            82126              32.7
Douglas County, Kansas: Summary level: 050, sta...           121436              32.7
Norfolk city, Virginia: Summary level: 050, sta...           244076              32.6
Monroe County, Indiana: Summary level: 050, sta...           146917              32.2
Monongalia County, West Virginia: Summary level...           106420              32.0
Payne County, Oklahoma: Summary level: 050, sta...            82040              31.8
Athens County, Ohio: Summary level: 050, state:...            65818              31.2
Arlington County, Virginia: Summary level: 050,...           237521              31.1
Centre County, Pennsylvania: Summary level: 050...           162805              31.0
Johnson County, Iowa: Summary level: 050, state...           151260              31.0
District of Columbia, District of Columbia: Sum...           702455              30.8
Tippecanoe County, Indiana: Summary level: 050,...           193048              30.7
Alachua County, Florida: Summary level: 050, st...           269956              30.7
Richmond city, Virginia: Summary level: 050, st...           228783              30.6
Grand Forks County, North Dakota: Summary level...            70770              30.6
Isabella County, Michigan: Summary level: 050, ...            70562              30.5
Benton County, Oregon: Summary level: 050, stat...            92101              30.3
Christian County, Kentucky: Summary level: 050,...            71671              30.3
Leon County, Florida: Summary level: 050, state...           292502              30.2
Blue Earth County, Minnesota: Summary level: 05...            67427              30.2
Boone County, Missouri: Summary level: 050, sta...           180005              29.8
Tompkins County, New York: Summary level: 050, ...           102793              29.6
Denver County, Colorado: Summary level: 050, st...           716492              29.3

In [13]:
#printing the labels 
censusdata.printtable(censusdata.censustable('acs1', 2018, 'DP05'))

Variable     | Table                          | Label                                                    | Type
-------------------------------------------------------------------------------------------------------------------
DP05_0001E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate SEX AND AGE Total population              | int
DP05_0001PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate SEX AND AGE Total population      | int
DP05_0002E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Male      | int
DP05_0002PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population M | float
DP05_0003E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Female    | int
DP05_0003PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population F | float
DP05_0004E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Sex ratio | float
DP05_0004PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population S | int
DP05_0005E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Under 5 y | int
DP05_0005PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population U | float
DP05_0006E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 5 to 9 ye | int
DP05_0006PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 5 | float
DP05_0007E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 10 to 14  | int
DP05_0007PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | float
DP05_0008E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 15 to 19  | int
DP05_0008PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | float
DP05_0009E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 20 to 24  | int
DP05_0009PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 2 | float
DP05_0010E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 25 to 34  | int
DP05_0010PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 2 | float
DP05_0011E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 35 to 44  | int
DP05_0011PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 3 | float
DP05_0012E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 45 to 54  | int
DP05_0012PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 4 | float
DP05_0013E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 55 to 59  | int
DP05_0013PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 5 | float
DP05_0014E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 60 to 64  | int
DP05_0014PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | float
DP05_0015E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 65 to 74  | int
DP05_0015PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | float
DP05_0016E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 75 to 84  | int
DP05_0016PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 7 | float
DP05_0017E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 85 years  | int
DP05_0017PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 8 | float
DP05_0018E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Median ag | float
DP05_0018PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population M | int
DP05_0019E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population Under 18  | int
DP05_0019PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population U | float
DP05_0020E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 16 years  | int
DP05_0020PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | float
DP05_0021E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 18 years  | int
DP05_0021PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | float
DP05_0022E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 21 years  | int
DP05_0022PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 2 | float
DP05_0023E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 62 years  | int
DP05_0023PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | float
DP05_0024E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 65 years  | int
DP05_0024PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | float
DP05_0025E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 18 years  | int
DP05_0025PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 1 | int
DP05_0026E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 18 yea | int
DP05_0026PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | float
DP05_0027E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 18 yea | int
DP05_0027PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | float
DP05_0028E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 18 yea | float
DP05_0028PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | int
DP05_0029E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate SEX AND AGE Total population 65 years  | int
DP05_0029PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate SEX AND AGE Total population 6 | int
DP05_0030E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 65 yea | int
DP05_0030PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | float
DP05_0031E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 65 yea | int
DP05_0031PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | float
DP05_0032E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate SEX AND AGE Total population 65 yea | float
DP05_0032PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate SEX AND AGE Total populatio | int
DP05_0033E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate RACE Total population                     | int
DP05_0033PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate RACE Total population             | int
DP05_0034E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate RACE Total population One race         | int
DP05_0034PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate RACE Total population One race | float
DP05_0035E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate RACE Total population Two or more race | int
DP05_0035PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate RACE Total population Two or m | float
DP05_0036E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate RACE Total population One race         | int
DP05_0036PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate RACE Total population One race | float
DP05_0037E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Whit | int
DP05_0037PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0038E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Blac | int
DP05_0038PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0039E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Amer | int
DP05_0039PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0040E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0040PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0041E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0041PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0042E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0042PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0043E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0043PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0044E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Asia | int
DP05_0044PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0045E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0045PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0046E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0046PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0047E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0047PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0048E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0048PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0049E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0049PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0050E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0050PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0051E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race A | int
DP05_0051PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0052E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Nati | int
DP05_0052PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0053E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race N | int
DP05_0053PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0054E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race N | int
DP05_0054PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0055E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race N | int
DP05_0055PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0056E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate RACE Total population One race N | int
DP05_0056PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate RACE Total population On | float
DP05_0057E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population One race Some | int
DP05_0057PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population One r | float
DP05_0058E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate RACE Total population Two or more race | int
DP05_0058PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate RACE Total population Two or m | float
DP05_0059E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population Two or more r | int
DP05_0059PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population Two o | float
DP05_0060E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population Two or more r | int
DP05_0060PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population Two o | float
DP05_0061E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population Two or more r | int
DP05_0061PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population Two o | float
DP05_0062E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate RACE Total population Two or more r | int
DP05_0062PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate RACE Total population Two o | float
DP05_0063E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate Race alone or in combination with one or  | int
DP05_0063PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate Race alone or in combination with | int
DP05_0064E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0064PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0065E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0065PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0066E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0066PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0067E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0067PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0068E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0068PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0069E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate Race alone or in combination with one  | int
DP05_0069PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate Race alone or in combination w | float
DP05_0070E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate HISPANIC OR LATINO AND RACE Total populat | int
DP05_0070PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate HISPANIC OR LATINO AND RACE Total | int
DP05_0071E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate HISPANIC OR LATINO AND RACE Total popu | int
DP05_0071PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE To | float
DP05_0072E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0072PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0073E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0073PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0074E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0074PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0075E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0075PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0076E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate HISPANIC OR LATINO AND RACE Total popu | int
DP05_0076PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE To | float
DP05_0077E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0077PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0078E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0078PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0079E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0079PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0080E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0080PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0081E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0081PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0082E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0082PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0083E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Total p | int
DP05_0083PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! Percent Estimate HISPANIC OR LATINO AND RACE | float
DP05_0084E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Tota | int
DP05_0084PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate HISPANIC OR LATINO AND R | float
DP05_0085E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Estimate HISPANIC OR LATINO AND RACE Tota | int
DP05_0085PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! !! !! Percent Estimate HISPANIC OR LATINO AND R | float
DP05_0086E   | ACS DEMOGRAPHIC AND HOUSING ES | !! Estimate Total housing units                          | int
DP05_0086PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! Percent Estimate Total housing units                  | int
DP05_0087E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Estimate CITIZEN, VOTING AGE POPULATION Citizen, 1 | int
DP05_0087PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! Percent Estimate CITIZEN, VOTING AGE POPULATION Ci | int
DP05_0088E   | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Estimate CITIZEN, VOTING AGE POPULATION Citizen | int
DP05_0088PE  | ACS DEMOGRAPHIC AND HOUSING ES | !! !! !! Percent Estimate CITIZEN, VOTING AGE POPULATION | float

In [14]:
#Help to download the data 
county_age_division = censusdata.download('acs1', 2018, censusdata.censusgeo([('county', '*')]),
                                   ['DP05_0001E', 'DP05_0005PE', 'DP05_0010PE'],
                                   tabletype='profile')

In [15]:
#Help to download the data 
county_age_division = censusdata.download('acs1', 2018, censusdata.censusgeo([('county', '*')]),
                                   ['DP05_0001E', 'DP05_0005PE','DP05_0006PE','DP05_0007PE','DP05_0008PE', 'DP05_0009PE','DP05_0010PE','DP05_0011PE','DP05_0012PE','DP05_0013PE','DP05_0014PE','DP05_0015PE','DP05_0016PE'],
                                   tabletype='profile')
county_age_division.head(10)

                                                    DP05_0001E  DP05_0005PE  DP05_0006PE  DP05_0007PE  DP05_0008PE  DP05_0009PE  DP05_0010PE  DP05_0011PE  DP05_0012PE  DP05_0013PE  DP05_0014PE  DP05_0015PE  DP05_0016PE
Morgan County, Alabama: Summary level: 050, sta...      119089          5.8          6.8          6.2          6.6          6.2         11.5         12.4         13.4          6.6          7.2         10.1          4.9
Kings County, California: Summary level: 050, s...      151366          7.3          7.8          7.7          7.1          7.8         16.7         14.3         11.6          5.9          3.7          5.8          3.5
Monterey County, California: Summary level: 050...      435594          7.1          7.2          7.7          6.9          7.3         14.2         13.1         11.7          5.6          5.5          7.9          3.8
Nevada County, California: Summary level: 050, ...       99696          3.9          4.5          6.1          4.3          3.5          9.9         11.5         11.6          8.0          8.9         17.5          7.1
Shasta County, California: Summary level: 050, ...      180040          5.5          6.6          5.7          5.8          5.8         12.4         11.2         11.5          7.2          7.7         11.9          6.4
Yuba County, California: Summary level: 050, st...       78041          7.6          6.8          8.3          7.1          6.7         15.7         12.2         10.8          5.6          7.2          7.4          3.3
Douglas County, Colorado: Summary level: 050, s...      342776          5.9          7.0          7.9          7.6          5.0         11.1         15.0         16.1          7.0          5.7          7.6          3.0
Fairfield County, Connecticut: Summary level: 0...      943823          5.5          5.9          6.9          7.0          6.3         11.4         12.4         14.6          7.3          6.7          8.7          4.9
Kent County, Delaware: Summary level: 050, stat...      178550          6.1          5.8          7.1          7.0          6.7         13.4         11.5         12.5          7.1          6.1          9.7          5.3
New Castle County, Delaware: Summary level: 050...      559335          5.8          5.6          6.4          6.6          6.5         14.5         12.4         13.3          7.0          6.4          9.1          4.6

In [16]:
#ch3cking the columns 
sorted(county_age_division)

['DP05_0001E',
 'DP05_0005PE',
 'DP05_0006PE',
 'DP05_0007PE',
 'DP05_0008PE',
 'DP05_0009PE',
 'DP05_0010PE',
 'DP05_0011PE',
 'DP05_0012PE',
 'DP05_0013PE',
 'DP05_0014PE',
 'DP05_0015PE',
 'DP05_0016PE']

In [17]:
county_age_division['percent_1to9'] = (county_age_division['DP05_0005PE'] + county_age_division['DP05_0006PE'])
county_age_division['percent_10to14'] = (county_age_division['DP05_0007PE'])
county_age_division['percent_15to19'] = (county_age_division['DP05_0008PE'])
county_age_division['percent_20to34'] = (county_age_division['DP05_0009PE'] + county_age_division['DP05_0010PE'])
county_age_division['percent_35to44'] = (county_age_division['DP05_0011PE'] + county_age_division['DP05_0012PE'])
county_age_division['percent_45to64'] = (county_age_division['DP05_0013PE'] + county_age_division['DP05_0014PE'])
county_age_division['percent_65plus'] = (county_age_division['DP05_0015PE'] + county_age_division['DP05_0016PE'])
county_age_division =county_age_division[['DP05_0001E', 'percent_1to9','percent_10to14','percent_15to19','percent_20to34','percent_35to44','percent_45to64','percent_65plus']]
county_age_division = county_age_division.rename(columns={'DP05_0001E': 'population_size'})
county_age_division.sort_values('population_size', ascending=False, inplace=True)
county_age_division.head(30)

                                                    population_size  percent_1to9  percent_10to14  percent_15to19  percent_20to34  percent_35to44  percent_45to64  percent_65plus
Los Angeles County, California: Summary level: ...         10105518          11.7             6.3             6.2            23.1            27.0            12.0            11.7
Cook County, Illinois: Summary level: 050, stat...          5180493          11.9             6.2             6.0            22.8            26.0            12.3            12.6
Harris County, Texas: Summary level: 050, state...          4698619          14.6             7.7             6.9            22.8            26.8            10.7             9.5
Maricopa County, Arizona: Summary level: 050, s...          4410824          12.7             7.0             6.7            21.2            25.5            11.5            13.4
San Diego County, California: Summary level: 05...          3343364          11.9             6.2             6.2            24.1            25.8            11.8            12.2
Orange County, California: Summary level: 050, ...          3185968          11.4             6.6             6.4            21.0            27.0            12.7            12.8
Miami-Dade County, Florida: Summary level: 050,...          2761581          11.1             5.7             5.7            20.4            28.4            12.5            13.7
Dallas County, Texas: Summary level: 050, state...          2637772          14.7             7.3             6.8            23.5            26.2            10.9             9.6
Kings County, New York: Summary level: 050, sta...          2582830          13.2             6.1             5.3            24.6            25.7            11.2            12.1
Riverside County, California: Summary level: 05...          2450758          13.4             7.4             7.2            20.9            25.3            11.5            12.7
Queens County, New York: Summary level: 050, st...          2278906          11.2             5.8             5.0            21.8            27.2            13.2            13.7
King County, Washington: Summary level: 050, st...          2233163          11.6             5.5             5.3            24.4            28.1            11.9            11.5
Clark County, Nevada: Summary level: 050, state...          2231647          12.5             6.9             6.1            20.9            27.1            11.8            13.3
San Bernardino County, California: Summary leve...          2171603          14.3             7.5             7.3            22.9            25.2            11.3            10.4
Tarrant County, Texas: Summary level: 050, stat...          2084931          14.3             7.6             7.1            21.6            26.7            11.5            10.0
Bexar County, Texas: Summary level: 050, state:...          1986049          13.8             7.6             7.2            23.3            25.4            10.6            10.9
Broward County, Florida: Summary level: 050, st...          1951260          11.1             6.4             5.7            19.2            27.5            13.4            14.6
Santa Clara County, California: Summary level: ...          1937570          11.6             6.6             5.9            22.4            28.2            11.8            11.5
Wayne County, Michigan: Summary level: 050, sta...          1753893          12.9             6.6             6.4            20.5            24.7            13.4            13.5
Alameda County, California: Summary level: 050,...          1666753          11.3             6.0             5.6            22.7            28.4            12.2            12.2
New York County, New York: Summary level: 050, ...          1628701           8.3             3.9             4.2            29.2            26.5            11.3            14.1
Middlesex County, Massachusetts: Summary level:...          1614714          10.8             5.5             6.4            22.7            26.5            12.9            13.1
Philadelphia County, Pennsylvania: Summary leve...          1584138          12.5             6.0             6.1            26.1            24.0            11.7            11.9
Sacramento County, California: Summary level: 0...          1540975          12.8             6.9             6.2            22.0            25.9            12.2            12.3
Palm Beach County, Florida: Summary level: 050,...          1485941          10.2             5.5             5.5            17.4            24.3            13.3            19.8
Suffolk County, New York: Summary level: 050, s...          1481093          10.8             6.4             6.6            18.4            26.5            14.5            14.8
Hillsborough County, Florida: Summary level: 05...          1436888          12.3             6.6             6.3            21.7            26.9            12.0            12.6
Bronx County, New York: Summary level: 050, sta...          1432132          13.8             7.0             6.7            23.4            25.1            11.2            11.3
Orange County, Florida: Summary level: 050, sta...          1380645          12.1             6.4             6.8            24.3            27.3            11.3            10.5
Nassau County, New York: Summary level: 050, st...          1358343          11.3             6.2             6.3            18.1            25.9            14.4            14.9

In [18]:
#Divide the education level 
#Working with the profile tables of Census 
censusdata.search('acs1', 2018, 'label', 'education', tabletype='profile')[-25:]

[('DP02PR_0066PE',
  'SELECTED SOCIAL CHARACTERISTICS IN PUERTO RICO',
  'Percent Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate or higher'),
 ('DP02PR_0067E',
  'SELECTED SOCIAL CHARACTERISTICS IN PUERTO RICO',
  "Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher"),
 ('DP02PR_0067PE',
  'SELECTED SOCIAL CHARACTERISTICS IN PUERTO RICO',
  "Percent Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher"),
 ('DP02_0058E',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over'),
 ('DP02_0058PE',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Percent Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over'),
 ('DP02_0059E',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Less than 9th grade'),
 ('DP02_0059PE',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Percent Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Less than 9th grade'),
 ('DP02_0060E',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!9th to 12th grade, no diploma'),
 ('DP02_0060PE',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Percent Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!9th to 12th grade, no diploma'),
 ('DP02_0061E',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate (includes equivalency)'),
 ('DP02_0061PE',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Percent Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate (includes equivalency)'),
 ('DP02_0062E',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Some college, no degree'),
 ('DP02_0062PE',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Percent Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Some college, no degree'),
 ('DP02_0063E',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  "Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Associate's degree"),
 ('DP02_0063PE',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  "Percent Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Associate's degree"),
 ('DP02_0064E',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  "Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree"),
 ('DP02_0064PE',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  "Percent Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree"),
 ('DP02_0065E',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Graduate or professional degree'),
 ('DP02_0065PE',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Percent Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Graduate or professional degree'),
 ('DP02_0066E',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate or higher'),
 ('DP02_0066PE',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  'Percent Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate or higher'),
 ('DP02_0067E',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  "Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher"),
 ('DP02_0067PE',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',
  "Percent Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher"),
 ('DP03_0042E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!INDUSTRY!!Civilian employed population 16 years and over!!Educational services, and health care and social assistance'),
 ('DP03_0042PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!INDUSTRY!!Civilian employed population 16 years and over!!Educational services, and health care and social assistance')]

In [19]:
#DP02_0058PE
#('DP02_0058PE',
  'SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',

('SELECTED SOCIAL CHARACTERISTICS IN THE UNITED STATES',)

In [20]:
#County education Level 
county_Education_division = censusdata.download('acs1', 2018, censusdata.censusgeo([('county', '*')]),
                                   ['DP05_0001E','DP02_0061PE','DP02_0064PE','DP02_0065PE','DP02_0067PE'],
                                   tabletype='profile')
county_Education_division.head(10)

                                                    DP05_0001E  DP02_0061PE  DP02_0064PE  DP02_0065PE  DP02_0067PE
Morgan County, Alabama: Summary level: 050, sta...      119089         28.7         17.7          8.1         25.8
Kings County, California: Summary level: 050, s...      151366         25.0         10.1          4.7         14.7
Monterey County, California: Summary level: 050...      435594         21.0         14.7         10.1         24.8
Nevada County, California: Summary level: 050, ...       99696         18.0         25.6         11.8         37.4
Shasta County, California: Summary level: 050, ...      180040         23.2         13.8          8.4         22.2
Yuba County, California: Summary level: 050, st...       78041         20.2         10.7          5.9         16.5
Douglas County, Colorado: Summary level: 050, s...      342776         11.8         38.3         20.0         58.4
Fairfield County, Connecticut: Summary level: 0...      943823         20.6         26.8         21.6         48.4
Kent County, Delaware: Summary level: 050, stat...      178550         32.6         13.5          9.8         23.3
New Castle County, Delaware: Summary level: 050...      559335         33.2         20.9         14.6         35.4

In [22]:

#County education Level 
county_Education_division = censusdata.download('acs1', 2018, censusdata.censusgeo([('county', '*')]),
                                   ['DP05_0001E','DP02_0061PE','DP02_0064PE','DP02_0065PE','DP02_0067PE'],
                                   tabletype='profile')
county_Education_division.head(10)

                                                    DP05_0001E  DP02_0061PE  DP02_0064PE  DP02_0065PE  DP02_0067PE
Morgan County, Alabama: Summary level: 050, sta...      119089         28.7         17.7          8.1         25.8
Kings County, California: Summary level: 050, s...      151366         25.0         10.1          4.7         14.7
Monterey County, California: Summary level: 050...      435594         21.0         14.7         10.1         24.8
Nevada County, California: Summary level: 050, ...       99696         18.0         25.6         11.8         37.4
Shasta County, California: Summary level: 050, ...      180040         23.2         13.8          8.4         22.2
Yuba County, California: Summary level: 050, st...       78041         20.2         10.7          5.9         16.5
Douglas County, Colorado: Summary level: 050, s...      342776         11.8         38.3         20.0         58.4
Fairfield County, Connecticut: Summary level: 0...      943823         20.6         26.8         21.6         48.4
Kent County, Delaware: Summary level: 050, stat...      178550         32.6         13.5          9.8         23.3
New Castle County, Delaware: Summary level: 050...      559335         33.2         20.9         14.6         35.4

In [23]:
#ch3cking the columns 
sorted(county_Education_division)

['DP02_0061PE', 'DP02_0064PE', 'DP02_0065PE', 'DP02_0067PE', 'DP05_0001E']

In [24]:
county_Education_division['percent_25year_above_high_school'] = (county_Education_division['DP02_0061PE'] )
county_Education_division['percent_25year_above_profeesional/assicate_diploma'] = (county_Education_division['DP02_0064PE'])
county_Education_division['percent_25year_above_bachelors_degree'] = (county_Education_division['DP02_0065PE'])
county_Education_division['percent_25year_above_bacholors and above'] = (county_Education_division['DP02_0067PE'] )
county_Education_division =county_Education_division[['DP05_0001E','percent_25year_above_high_school','percent_25year_above_profeesional/assicate_diploma','percent_25year_above_bachelors_degree','percent_25year_above_bacholors and above' ]]
county_Education_division = county_Education_division.rename(columns={'DP05_0001E': 'population_size'})
county_Education_division.sort_values('population_size', ascending=False, inplace=True)
county_Education_division.head(30)

                                                    population_size  percent_25year_above_high_school  percent_25year_above_profeesional/assicate_diploma  percent_25year_above_bachelors_degree  percent_25year_above_bacholors and above
Los Angeles County, California: Summary level: ...         10105518                              20.6                                               21.3                                    11.2                                      32.5
Cook County, Illinois: Summary level: 050, stat...          5180493                              23.5                                               23.0                                    16.3                                      39.3
Harris County, Texas: Summary level: 050, state...          4698619                              23.4                                               19.9                                    11.7                                      31.6
Maricopa County, Arizona: Summary level: 050, s...          4410824                              22.3                                               21.0                                    12.2                                      33.2
San Diego County, California: Summary level: 05...          3343364                              18.5                                               23.1                                    15.3                                      38.4
Orange County, California: Summary level: 050, ...          3185968                              17.2                                               26.4                                    14.7                                      41.0
Miami-Dade County, Florida: Summary level: 050,...          2761581                              26.9                                               19.9                                    11.6                                      31.4
Dallas County, Texas: Summary level: 050, state...          2637772                              23.2                                               20.0                                    11.7                                      31.8
Kings County, New York: Summary level: 050, sta...          2582830                              25.8                                               23.3                                    15.6                                      38.9
Riverside County, California: Summary level: 05...          2450758                              29.3                                               14.2                                     8.1                                      22.2
Queens County, New York: Summary level: 050, st...          2278906                              26.9                                               21.0                                    12.4                                      33.5
King County, Washington: Summary level: 050, st...          2233163                              15.1                                               31.7                                    21.5                                      53.2
Clark County, Nevada: Summary level: 050, state...          2231647                              28.1                                               16.1                                     8.5                                      24.6
San Bernardino County, California: Summary leve...          2171603                              26.7                                               13.9                                     7.5                                      21.4
Tarrant County, Texas: Summary level: 050, stat...          2084931                              24.3                                               21.4                                    10.8                                      32.2
Bexar County, Texas: Summary level: 050, state:...          1986049                              25.9                                               17.0                                    10.1                                      27.1
Broward County, Florida: Summary level: 050, st...          1951260                              27.2                                               19.8                                    12.6                                      32.3
Santa Clara County, California: Summary level: ...          1937570                              13.7                                               28.4                                    25.4                                      53.8
Wayne County, Michigan: Summary level: 050, sta...          1753893                              29.8                                               15.1                                    10.0                                      25.1
Alameda County, California: Summary level: 050,...          1666753                              18.1                                               27.5                                    20.8                                      48.3
New York County, New York: Summary level: 050, ...          1628701                              13.1                                               32.1                                    29.2                                      61.4
Middlesex County, Massachusetts: Summary level:...          1614714                              18.4                                               28.4                                    29.4                                      57.8
Philadelphia County, Pennsylvania: Summary leve...          1584138                              33.1                                               17.7                                    13.2                                      30.9
Sacramento County, California: Summary level: 0...          1540975                              22.0                                               20.8                                    10.6                                      31.4
Palm Beach County, Florida: Summary level: 050,...          1485941                              24.4                                               22.7                                    14.2                                      36.9
Suffolk County, New York: Summary level: 050, s...          1481093                              27.4                                               20.0                                    16.9                                      36.9
Hillsborough County, Florida: Summary level: 05...          1436888                              27.8                                               21.6                                    12.4                                      34.0
Bronx County, New York: Summary level: 050, sta...          1432132                              27.7                                               13.4                                     7.3                                      20.7
Orange County, Florida: Summary level: 050, sta...          1380645                              24.5                                               23.4                                    12.4                                      35.7
Nassau County, New York: Summary level: 050, st...          1358343                              22.9                                               25.2                                    21.1                                      46.3

In [25]:
#checking For occupation 
censusdata.search('acs1', 2018, 'label', 'occupation', tabletype='profile')[-25:]

[('DP03_0026E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!OCCUPATION!!Civilian employed population 16 years and over'),
 ('DP03_0026PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!OCCUPATION!!Civilian employed population 16 years and over'),
 ('DP03_0027E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Management, business, science, and arts occupations'),
 ('DP03_0027PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Management, business, science, and arts occupations'),
 ('DP03_0028E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Service occupations'),
 ('DP03_0028PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Service occupations'),
 ('DP03_0029E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Sales and office occupations'),
 ('DP03_0029PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Sales and office occupations'),
 ('DP03_0030E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Natural resources, construction, and maintenance occupations'),
 ('DP03_0030PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Natural resources, construction, and maintenance occupations'),
 ('DP03_0031E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Production, transportation, and material moving occupations'),
 ('DP03_0031PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Production, transportation, and material moving occupations')]

In [26]:
censusdata.printtable(censusdata.censustable('acs1', 2018, 'DP03'))

Variable     | Table                          | Label                                                    | Type
-------------------------------------------------------------------------------------------------------------------
DP03_0001E   | SELECTED ECONOMIC CHARACTERIST | !! !! Estimate EMPLOYMENT STATUS Population 16 years and | int
DP03_0001PE  | SELECTED ECONOMIC CHARACTERIST | !! !! Percent Estimate EMPLOYMENT STATUS Population 16 y | int
DP03_0002E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate EMPLOYMENT STATUS Population 16 years  | int
DP03_0002PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate EMPLOYMENT STATUS Population 1 | float
DP03_0003E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Estimate EMPLOYMENT STATUS Population 16 yea | int
DP03_0003PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Percent Estimate EMPLOYMENT STATUS Populatio | float
DP03_0004E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! !! Estimate EMPLOYMENT STATUS Population 16  | int
DP03_0004PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! !! Percent Estimate EMPLOYMENT STATUS Popula | float
DP03_0005E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! !! Estimate EMPLOYMENT STATUS Population 16  | int
DP03_0005PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! !! Percent Estimate EMPLOYMENT STATUS Popula | float
DP03_0006E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Estimate EMPLOYMENT STATUS Population 16 yea | int
DP03_0006PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Percent Estimate EMPLOYMENT STATUS Populatio | float
DP03_0007E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate EMPLOYMENT STATUS Population 16 years  | int
DP03_0007PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate EMPLOYMENT STATUS Population 1 | float
DP03_0008E   | SELECTED ECONOMIC CHARACTERIST | !! !! Estimate EMPLOYMENT STATUS Civilian labor force    | int
DP03_0008PE  | SELECTED ECONOMIC CHARACTERIST | !! !! Percent Estimate EMPLOYMENT STATUS Civilian labor  | int
DP03_0009E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate EMPLOYMENT STATUS Civilian labor force | float
DP03_0009PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate EMPLOYMENT STATUS Civilian lab | float
DP03_0010E   | SELECTED ECONOMIC CHARACTERIST | !! !! Estimate EMPLOYMENT STATUS Females 16 years and ov | int
DP03_0010PE  | SELECTED ECONOMIC CHARACTERIST | !! !! Percent Estimate EMPLOYMENT STATUS Females 16 year | int
DP03_0011E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate EMPLOYMENT STATUS Females 16 years and | int
DP03_0011PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate EMPLOYMENT STATUS Females 16 y | float
DP03_0012E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Estimate EMPLOYMENT STATUS Females 16 years  | int
DP03_0012PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Percent Estimate EMPLOYMENT STATUS Females 1 | float
DP03_0013E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! !! Estimate EMPLOYMENT STATUS Females 16 yea | int
DP03_0013PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! !! Percent Estimate EMPLOYMENT STATUS Female | float
DP03_0014E   | SELECTED ECONOMIC CHARACTERIST | !! !! Estimate EMPLOYMENT STATUS Own children of the hou | int
DP03_0014PE  | SELECTED ECONOMIC CHARACTERIST | !! !! Percent Estimate EMPLOYMENT STATUS Own children of | int
DP03_0015E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate EMPLOYMENT STATUS Own children of the  | int
DP03_0015PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate EMPLOYMENT STATUS Own children | float
DP03_0016E   | SELECTED ECONOMIC CHARACTERIST | !! !! Estimate EMPLOYMENT STATUS Own children of the hou | int
DP03_0016PE  | SELECTED ECONOMIC CHARACTERIST | !! !! Percent Estimate EMPLOYMENT STATUS Own children of | int
DP03_0017E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate EMPLOYMENT STATUS Own children of the  | int
DP03_0017PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate EMPLOYMENT STATUS Own children | float
DP03_0018E   | SELECTED ECONOMIC CHARACTERIST | !! !! Estimate COMMUTING TO WORK Workers 16 years and ov | int
DP03_0018PE  | SELECTED ECONOMIC CHARACTERIST | !! !! Percent Estimate COMMUTING TO WORK Workers 16 year | int
DP03_0019E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate COMMUTING TO WORK Workers 16 years and | int
DP03_0019PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate COMMUTING TO WORK Workers 16 y | float
DP03_0020E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate COMMUTING TO WORK Workers 16 years and | int
DP03_0020PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate COMMUTING TO WORK Workers 16 y | float
DP03_0021E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate COMMUTING TO WORK Workers 16 years and | int
DP03_0021PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate COMMUTING TO WORK Workers 16 y | float
DP03_0022E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate COMMUTING TO WORK Workers 16 years and | int
DP03_0022PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate COMMUTING TO WORK Workers 16 y | float
DP03_0023E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate COMMUTING TO WORK Workers 16 years and | int
DP03_0023PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate COMMUTING TO WORK Workers 16 y | float
DP03_0024E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate COMMUTING TO WORK Workers 16 years and | int
DP03_0024PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate COMMUTING TO WORK Workers 16 y | float
DP03_0025E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate COMMUTING TO WORK Workers 16 years and | float
DP03_0025PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate COMMUTING TO WORK Workers 16 y | int
DP03_0026E   | SELECTED ECONOMIC CHARACTERIST | !! !! Estimate OCCUPATION Civilian employed population 1 | int
DP03_0026PE  | SELECTED ECONOMIC CHARACTERIST | !! !! Percent Estimate OCCUPATION Civilian employed popu | int
DP03_0027E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate OCCUPATION Civilian employed populatio | int
DP03_0027PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate OCCUPATION Civilian employed p | float
DP03_0028E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate OCCUPATION Civilian employed populatio | int
DP03_0028PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate OCCUPATION Civilian employed p | float
DP03_0029E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate OCCUPATION Civilian employed populatio | int
DP03_0029PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate OCCUPATION Civilian employed p | float
DP03_0030E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate OCCUPATION Civilian employed populatio | int
DP03_0030PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate OCCUPATION Civilian employed p | float
DP03_0031E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate OCCUPATION Civilian employed populatio | int
DP03_0031PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate OCCUPATION Civilian employed p | float
DP03_0032E   | SELECTED ECONOMIC CHARACTERIST | !! !! Estimate INDUSTRY Civilian employed population 16  | int
DP03_0032PE  | SELECTED ECONOMIC CHARACTERIST | !! !! Percent Estimate INDUSTRY Civilian employed popula | int
DP03_0033E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INDUSTRY Civilian employed population  | int
DP03_0033PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INDUSTRY Civilian employed pop | float
DP03_0034E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INDUSTRY Civilian employed population  | int
DP03_0034PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INDUSTRY Civilian employed pop | float
DP03_0035E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INDUSTRY Civilian employed population  | int
DP03_0035PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INDUSTRY Civilian employed pop | float
DP03_0036E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INDUSTRY Civilian employed population  | int
DP03_0036PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INDUSTRY Civilian employed pop | float
DP03_0037E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INDUSTRY Civilian employed population  | int
DP03_0037PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INDUSTRY Civilian employed pop | float
DP03_0038E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INDUSTRY Civilian employed population  | int
DP03_0038PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INDUSTRY Civilian employed pop | float
DP03_0039E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INDUSTRY Civilian employed population  | int
DP03_0039PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INDUSTRY Civilian employed pop | float
DP03_0040E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INDUSTRY Civilian employed population  | int
DP03_0040PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INDUSTRY Civilian employed pop | float
DP03_0041E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INDUSTRY Civilian employed population  | int
DP03_0041PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INDUSTRY Civilian employed pop | float
DP03_0042E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INDUSTRY Civilian employed population  | int
DP03_0042PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INDUSTRY Civilian employed pop | float
DP03_0043E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INDUSTRY Civilian employed population  | int
DP03_0043PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INDUSTRY Civilian employed pop | float
DP03_0044E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INDUSTRY Civilian employed population  | int
DP03_0044PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INDUSTRY Civilian employed pop | float
DP03_0045E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INDUSTRY Civilian employed population  | int
DP03_0045PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INDUSTRY Civilian employed pop | float
DP03_0046E   | SELECTED ECONOMIC CHARACTERIST | !! !! Estimate CLASS OF WORKER Civilian employed populat | int
DP03_0046PE  | SELECTED ECONOMIC CHARACTERIST | !! !! Percent Estimate CLASS OF WORKER Civilian employed | int
DP03_0047E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate CLASS OF WORKER Civilian employed popu | int
DP03_0047PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate CLASS OF WORKER Civilian emplo | float
DP03_0048E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate CLASS OF WORKER Civilian employed popu | int
DP03_0048PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate CLASS OF WORKER Civilian emplo | float
DP03_0049E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate CLASS OF WORKER Civilian employed popu | int
DP03_0049PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate CLASS OF WORKER Civilian emplo | float
DP03_0050E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate CLASS OF WORKER Civilian employed popu | int
DP03_0050PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate CLASS OF WORKER Civilian emplo | float
DP03_0051E   | SELECTED ECONOMIC CHARACTERIST | !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION-AD | int
DP03_0051PE  | SELECTED ECONOMIC CHARACTERIST | !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 INFL | int
DP03_0052E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0052PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0053E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0053PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0054E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0054PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0055E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0055PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0056E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0056PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0057E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0057PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0058E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0058PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0059E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0059PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0060E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0060PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0061E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0061PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0062E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0062PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | int
DP03_0063E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0063PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | int
DP03_0064E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0064PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0065E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLAT | int
DP03_0065PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Percent Estimate INCOME AND BENEFITS (IN 201 | int
DP03_0066E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0066PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0067E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLAT | int
DP03_0067PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Percent Estimate INCOME AND BENEFITS (IN 201 | int
DP03_0068E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0068PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0069E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLAT | int
DP03_0069PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Percent Estimate INCOME AND BENEFITS (IN 201 | int
DP03_0070E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0070PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0071E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLAT | int
DP03_0071PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Percent Estimate INCOME AND BENEFITS (IN 201 | int
DP03_0072E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0072PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0073E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLAT | int
DP03_0073PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! !! Percent Estimate INCOME AND BENEFITS (IN 201 | int
DP03_0074E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0074PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0075E   | SELECTED ECONOMIC CHARACTERIST | !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION-AD | int
DP03_0075PE  | SELECTED ECONOMIC CHARACTERIST | !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 INFL | int
DP03_0076E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0076PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0077E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0077PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0078E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0078PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0079E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0079PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0080E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0080PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0081E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0081PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0082E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0082PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0083E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0083PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0084E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0084PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0085E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0085PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | float
DP03_0086E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0086PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | int
DP03_0087E   | SELECTED ECONOMIC CHARACTERIST | !! !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION | int
DP03_0087PE  | SELECTED ECONOMIC CHARACTERIST | !! !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 I | int
DP03_0088E   | SELECTED ECONOMIC CHARACTERIST | !! !! Estimate INCOME AND BENEFITS (IN 2018 INFLATION-AD | int
DP03_0088PE  | SELECTED ECONOMIC CHARACTERIST | !! !! Percent Estimate INCOME AND BENEFITS (IN 2018 INFL | int

In [27]:
#checking For occupation 
censusdata.search('acs1', 2018, 'label', 'occupation', tabletype='profile')[-25:]

[('DP03_0026E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!OCCUPATION!!Civilian employed population 16 years and over'),
 ('DP03_0026PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!OCCUPATION!!Civilian employed population 16 years and over'),
 ('DP03_0027E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Management, business, science, and arts occupations'),
 ('DP03_0027PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Management, business, science, and arts occupations'),
 ('DP03_0028E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Service occupations'),
 ('DP03_0028PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Service occupations'),
 ('DP03_0029E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Sales and office occupations'),
 ('DP03_0029PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Sales and office occupations'),
 ('DP03_0030E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Natural resources, construction, and maintenance occupations'),
 ('DP03_0030PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Natural resources, construction, and maintenance occupations'),
 ('DP03_0031E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Production, transportation, and material moving occupations'),
 ('DP03_0031PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!OCCUPATION!!Civilian employed population 16 years and over!!Production, transportation, and material moving occupations')]

In [28]:
#DP03_0027PE-Management, business, science, and arts occupations
#DP03_0028PE-Service occupations
#DP03_0029PE-Sales and office occupations
#DP03_0030PE-Natural resources, construction, and maintenance occupations
#DP03_0031PE-Production, transportation, and material moving occupations

In [29]:
#County occupation Level 
county_occupation_division = censusdata.download('acs1', 2018, censusdata.censusgeo([('county', '*')]),
                                   ['DP05_0001E','DP03_0027PE','DP03_0028PE','DP03_0029PE','DP03_0030PE','DP03_0031PE'],
                                   tabletype='profile')
county_occupation_division.head(10)

                                                    DP05_0001E  DP03_0027PE  DP03_0028PE  DP03_0029PE  DP03_0030PE  DP03_0031PE
Morgan County, Alabama: Summary level: 050, sta...      119089         34.8         14.5         21.6          9.5         19.6
Kings County, California: Summary level: 050, s...      151366         27.1         20.3         16.6         20.7         15.3
Monterey County, California: Summary level: 050...      435594         28.1         20.2         18.4         19.4         13.8
Nevada County, California: Summary level: 050, ...       99696         39.2         19.4         23.8          9.4          8.2
Shasta County, California: Summary level: 050, ...      180040         35.1         22.2         20.7         11.4         10.6
Yuba County, California: Summary level: 050, st...       78041         24.8         23.8         21.0         17.2         13.2
Douglas County, Colorado: Summary level: 050, s...      342776         55.0         12.7         22.9          3.8          5.7
Fairfield County, Connecticut: Summary level: 0...      943823         45.6         17.3         21.7          7.6          7.7
Kent County, Delaware: Summary level: 050, stat...      178550         30.9         21.6         23.2          8.6         15.6
New Castle County, Delaware: Summary level: 050...      559335         43.7         16.9         21.6          7.5         10.3

In [30]:
county_occupation_division['Management_business_science_arts'] = (county_occupation_division['DP03_0027PE'] )
county_occupation_division['Service_occupations'] = (county_occupation_division['DP03_0028PE'])
county_occupation_division['Sales_&_office_occupation'] = (county_occupation_division['DP03_0029PE'])
county_occupation_division['Naturalresources_construction_maintenance'] = (county_occupation_division['DP03_0030PE'] )
county_occupation_division['Production_transportation_materialmoving'] = (county_occupation_division['DP03_0031PE'] )
county_occupation_division =county_occupation_division[['DP05_0001E','Management_business_science_arts','Service_occupations','Sales_&_office_occupation','Naturalresources_construction_maintenance','Production_transportation_materialmoving' ]]
county_occupation_division =county_occupation_division.rename(columns={'DP05_0001E': 'population_size'})
county_occupation_division.sort_values('population_size', ascending=False, inplace=True)
county_occupation_division.head(30)

                                                    population_size  Management_business_science_arts  Service_occupations  Sales_&_office_occupation  Naturalresources_construction_maintenance  Production_transportation_materialmoving
Los Angeles County, California: Summary level: ...         10105518                              37.3                 19.4                       21.7                                        7.8                                      13.8
Cook County, Illinois: Summary level: 050, stat...          5180493                              41.3                 17.8                       21.6                                        5.7                                      13.6
Harris County, Texas: Summary level: 050, state...          4698619                              35.9                 17.5                       20.8                                       12.1                                      13.7
Maricopa County, Arizona: Summary level: 050, s...          4410824                              38.2                 18.4                       24.1                                        8.0                                      11.3
San Diego County, California: Summary level: 05...          3343364                              41.3                 19.8                       21.2                                        7.6                                      10.1
Orange County, California: Summary level: 050, ...          3185968                              42.9                 17.5                       23.6                                        5.9                                      10.2
Miami-Dade County, Florida: Summary level: 050,...          2761581                              32.6                 20.7                       25.2                                       10.1                                      11.4
Dallas County, Texas: Summary level: 050, state...          2637772                              34.8                 17.1                       22.1                                       11.8                                      14.2
Kings County, New York: Summary level: 050, sta...          2582830                              43.7                 22.7                       19.1                                        5.7                                       8.9
Riverside County, California: Summary level: 05...          2450758                              29.5                 21.2                       23.4                                       11.0                                      15.0
Queens County, New York: Summary level: 050, st...          2278906                              34.7                 24.2                       20.3                                        8.6                                      12.2
King County, Washington: Summary level: 050, st...          2233163                              53.1                 14.6                       18.4                                        5.2                                       8.7
Clark County, Nevada: Summary level: 050, state...          2231647                              29.4                 27.1                       23.8                                        8.2                                      11.5
San Bernardino County, California: Summary leve...          2171603                              29.5                 18.4                       21.5                                       10.8                                      19.9
Tarrant County, Texas: Summary level: 050, stat...          2084931                              35.7                 15.4                       23.5                                        9.6                                      15.9
Bexar County, Texas: Summary level: 050, state:...          1986049                              34.7                 20.0                       23.7                                       10.0                                      11.6
Broward County, Florida: Summary level: 050, st...          1951260                              35.9                 20.3                       25.1                                        8.5                                      10.3
Santa Clara County, California: Summary level: ...          1937570                              54.5                 14.4                       17.0                                        5.9                                       8.2
Wayne County, Michigan: Summary level: 050, sta...          1753893                              33.1                 19.6                       21.0                                        6.7                                      19.6
Alameda County, California: Summary level: 050,...          1666753                              51.4                 14.8                       17.6                                        6.1                                      10.2
New York County, New York: Summary level: 050, ...          1628701                              60.7                 14.2                       18.4                                        2.1                                       4.5
Middlesex County, Massachusetts: Summary level:...          1614714                              58.0                 13.9                       16.7                                        5.1                                       6.3
Philadelphia County, Pennsylvania: Summary leve...          1584138                              39.7                 22.5                       19.7                                        5.6                                      12.5
Sacramento County, California: Summary level: 0...          1540975                              39.6                 18.9                       22.6                                        8.0                                      10.9
Palm Beach County, Florida: Summary level: 050,...          1485941                              37.0                 22.8                       22.6                                        8.7                                       8.8
Suffolk County, New York: Summary level: 050, s...          1481093                              40.7                 17.5                       23.6                                        8.8                                       9.5
Hillsborough County, Florida: Summary level: 05...          1436888                              39.0                 17.2                       25.1                                        9.0                                       9.7
Bronx County, New York: Summary level: 050, sta...          1432132                              25.0                 34.1                       21.8                                        6.2                                      12.9
Orange County, Florida: Summary level: 050, sta...          1380645                              37.3                 19.3                       24.9                                        8.3                                      10.2
Nassau County, New York: Summary level: 050, st...          1358343                              46.4                 16.5                       23.3                                        6.2                                       7.7

In [31]:
#checking For occupation 
censusdata.search('acs1', 2018, 'label', 'earning', tabletype='profile')[-25:]

[('DP03_0064E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Total households!!With earnings'),
 ('DP03_0064PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Total households!!With earnings'),
 ('DP03_0065E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Total households!!With earnings!!Mean earnings (dollars)'),
 ('DP03_0065PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Total households!!With earnings!!Mean earnings (dollars)'),
 ('DP03_0092E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Median earnings for workers (dollars)'),
 ('DP03_0092PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Median earnings for workers (dollars)'),
 ('DP03_0093E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Median earnings for male full-time, year-round workers (dollars)'),
 ('DP03_0093PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Median earnings for male full-time, year-round workers (dollars)'),
 ('DP03_0094E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Median earnings for female full-time, year-round workers (dollars)'),
 ('DP03_0094PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Median earnings for female full-time, year-round workers (dollars)')]

In [32]:
#County median_earning Level 
county_earning_division = censusdata.download('acs1', 2018, censusdata.censusgeo([('county', '*')]),
                                   ['DP05_0001E','DP03_0092E','DP03_0093E','DP03_0094E'],
                                   tabletype='profile')
county_earning_division.head(10)

                                                    DP05_0001E  DP03_0092E  DP03_0093E  DP03_0094E
Morgan County, Alabama: Summary level: 050, sta...      119089       31041       44515       33244
Kings County, California: Summary level: 050, s...      151366       32168       46110       44562
Monterey County, California: Summary level: 050...      435594       30039       42897       40231
Nevada County, California: Summary level: 050, ...       99696       34785       56197       47745
Shasta County, California: Summary level: 050, ...      180040       30955       57426       44493
Yuba County, California: Summary level: 050, st...       78041       28356       40852       36667
Douglas County, Colorado: Summary level: 050, s...      342776       55346       94669       60936
Fairfield County, Connecticut: Summary level: 0...      943823       43323       74665       60874
Kent County, Delaware: Summary level: 050, stat...      178550       32114       46034       39380
New Castle County, Delaware: Summary level: 050...      559335       37855       58084       47868

In [33]:
#Renaming the Columns 
county_earning_division['Median_household_income'] = (county_earning_division['DP03_0092E'] )
county_earning_division['Median_houshold_year_round_incomes'] = (county_earning_division['DP03_0093E'])+ (county_earning_division['DP03_0094E'])
county_earning_division =county_earning_division[['DP05_0001E','Median_household_income','Median_houshold_year_round_incomes']]
county_earning_division =county_earning_division.rename(columns={'DP05_0001E': 'population_size'})
county_earning_division.sort_values('population_size', ascending=False, inplace=True)
county_earning_division.head(30)

                                                    population_size  Median_household_income  Median_houshold_year_round_incomes
Los Angeles County, California: Summary level: ...         10105518                    33635                               92811
Cook County, Illinois: Summary level: 050, stat...          5180493                    39986                              106353
Harris County, Texas: Summary level: 050, state...          4698619                    33996                               89459
Maricopa County, Arizona: Summary level: 050, s...          4410824                    35452                               91648
San Diego County, California: Summary level: 05...          3343364                    36890                              104344
Orange County, California: Summary level: 050, ...          3185968                    40419                              113209
Miami-Dade County, Florida: Summary level: 050,...          2761581                    30280                               73596
Dallas County, Texas: Summary level: 050, state...          2637772                    35058                               87113
Kings County, New York: Summary level: 050, sta...          2582830                    40764                              107751
Riverside County, California: Summary level: 05...          2450758                    31936                               91517
Queens County, New York: Summary level: 050, st...          2278906                    38642                               97877
King County, Washington: Summary level: 050, st...          2233163                    50875                              141689
Clark County, Nevada: Summary level: 050, state...          2231647                    33537                               84738
San Bernardino County, California: Summary leve...          2171603                    32086                               88084
Tarrant County, Texas: Summary level: 050, stat...          2084931                    35964                               92927
Bexar County, Texas: Summary level: 050, state:...          1986049                    30316                               80066
Broward County, Florida: Summary level: 050, st...          1951260                    32612                               87371
Santa Clara County, California: Summary level: ...          1937570                    57158                              163127
Wayne County, Michigan: Summary level: 050, sta...          1753893                    31449                               91133
Alameda County, California: Summary level: 050,...          1666753                    52049                              141390
New York County, New York: Summary level: 050, ...          1628701                    61224                              167179
Middlesex County, Massachusetts: Summary level:...          1614714                    51311                              143156
Philadelphia County, Pennsylvania: Summary leve...          1584138                    32550                               92844
Sacramento County, California: Summary level: 0...          1540975                    37071                              103429
Palm Beach County, Florida: Summary level: 050,...          1485941                    32024                               90987
Suffolk County, New York: Summary level: 050, s...          1481093                    46976                              124498
Hillsborough County, Florida: Summary level: 05...          1436888                    34470                               90791
Bronx County, New York: Summary level: 050, sta...          1432132                    27672                               80735
Orange County, Florida: Summary level: 050, sta...          1380645                    30731                               80477
Nassau County, New York: Summary level: 050, st...          1358343                    51306                              140903

In [34]:
#checking dataframe info
county_earning_division.info()

<class 'pandas.core.frame.DataFrame'>
Index: 838 entries, Los Angeles County, California: Summary level: 050, state:06> county:037 to Salem County, New Jersey: Summary level: 050, state:34> county:033
Data columns (total 3 columns):
population_size                       838 non-null int64
Median_household_income               838 non-null int64
Median_houshold_year_round_incomes    838 non-null int64
dtypes: int64(3)
memory usage: 26.2+ KB

In [35]:
#checking For occupation 
censusdata.search('acs1', 2018, 'label', 'year-round', tabletype='profile')[-25:]

[('DP03_0093E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Median earnings for male full-time, year-round workers (dollars)'),
 ('DP03_0093PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Median earnings for male full-time, year-round workers (dollars)'),
 ('DP03_0094E',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Median earnings for female full-time, year-round workers (dollars)'),
 ('DP03_0094PE',
  'SELECTED ECONOMIC CHARACTERISTICS',
  'Percent Estimate!!INCOME AND BENEFITS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Median earnings for female full-time, year-round workers (dollars)')]

In [36]:
# setting county name as index column 
county_age_division=county_age_division.rename_axis('state')
county_Education_division=county_Education_division.rename_axis('state')
county_occupation_division=county_occupation_division.rename_axis('state')
county_earning_division=county_earning_division.rename_axis('state')

In [37]:
#Display
county_earning_division.head(10)

                                                    population_size  Median_household_income  Median_houshold_year_round_incomes
state
Los Angeles County, California: Summary level: ...         10105518                    33635                               92811
Cook County, Illinois: Summary level: 050, stat...          5180493                    39986                              106353
Harris County, Texas: Summary level: 050, state...          4698619                    33996                               89459
Maricopa County, Arizona: Summary level: 050, s...          4410824                    35452                               91648
San Diego County, California: Summary level: 05...          3343364                    36890                              104344
Orange County, California: Summary level: 050, ...          3185968                    40419                              113209
Miami-Dade County, Florida: Summary level: 050,...          2761581                    30280                               73596
Dallas County, Texas: Summary level: 050, state...          2637772                    35058                               87113
Kings County, New York: Summary level: 050, sta...          2582830                    40764                              107751
Riverside County, California: Summary level: 05...          2450758                    31936                               91517

In [38]:
county_earning_division.info()

<class 'pandas.core.frame.DataFrame'>
Index: 838 entries, Los Angeles County, California: Summary level: 050, state:06> county:037 to Salem County, New Jersey: Summary level: 050, state:34> county:033
Data columns (total 3 columns):
population_size                       838 non-null int64
Median_household_income               838 non-null int64
Median_houshold_year_round_incomes    838 non-null int64
dtypes: int64(3)
memory usage: 26.2+ KB

In [40]:
county_earning_division.reset_index(level=0, inplace=True)

In [41]:
county_earning_division.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 838 entries, 0 to 837
Data columns (total 5 columns):
index                                 838 non-null int64
state                                 838 non-null object
population_size                       838 non-null int64
Median_household_income               838 non-null int64
Median_houshold_year_round_incomes    838 non-null int64
dtypes: int64(4), object(1)
memory usage: 32.9+ KB

In [42]:
#Resetting the index and making state as column 
county_age_division.reset_index(level=0, inplace=True)
county_Education_division.reset_index(level=0, inplace=True)
county_occupation_division.reset_index(level=0, inplace=True)

In [43]:
county_age_division.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 838 entries, 0 to 837
Data columns (total 9 columns):
state              838 non-null object
population_size    838 non-null int64
percent_1to9       838 non-null float64
percent_10to14     838 non-null float64
percent_15to19     838 non-null float64
percent_20to34     838 non-null float64
percent_35to44     838 non-null float64
percent_45to64     838 non-null float64
percent_65plus     838 non-null float64
dtypes: float64(7), int64(1), object(1)
memory usage: 59.0+ KB

In [44]:
county_Education_division.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 838 entries, 0 to 837
Data columns (total 6 columns):
state                                                 838 non-null object
population_size                                       838 non-null int64
percent_25year_above_high_school                      827 non-null float64
percent_25year_above_profeesional/assicate_diploma    827 non-null float64
percent_25year_above_bachelors_degree                 827 non-null float64
percent_25year_above_bacholors and above              827 non-null float64
dtypes: float64(4), int64(1), object(1)
memory usage: 39.4+ KB

In [45]:
county_occupation_division.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 838 entries, 0 to 837
Data columns (total 7 columns):
state                                        838 non-null object
population_size                              838 non-null int64
Management_business_science_arts             838 non-null float64
Service_occupations                          838 non-null float64
Sales_&_office_occupation                    838 non-null float64
Naturalresources_construction_maintenance    838 non-null float64
Production_transportation_materialmoving     838 non-null float64
dtypes: float64(5), int64(1), object(1)
memory usage: 46.0+ KB

In [46]:
county_occupation_division['state']=county_occupation_division['state'].astype(str)

In [47]:
county_occupation_division.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 838 entries, 0 to 837
Data columns (total 7 columns):
state                                        838 non-null object
population_size                              838 non-null int64
Management_business_science_arts             838 non-null float64
Service_occupations                          838 non-null float64
Sales_&_office_occupation                    838 non-null float64
Naturalresources_construction_maintenance    838 non-null float64
Production_transportation_materialmoving     838 non-null float64
dtypes: float64(5), int64(1), object(1)
memory usage: 46.0+ KB

In [ ]:
#County_age_division.
#county_Education_division
#County_occupation_division
#county_earning_division

In [48]:
county_occupation_division.to_csv(r'C:\Users\kaurb\OneDrive\Desktop\class Folder\Final_challenge\County_occupation_division.csv', index=False)

In [49]:
county_age_division.to_csv(r'C:\Users\kaurb\OneDrive\Desktop\class Folder\Final_challenge\County_age_division.csv', index=False)

In [50]:
county_Education_division.to_csv(r'C:\Users\kaurb\OneDrive\Desktop\class Folder\Final_challenge\county_Education_division.csv', index=False)

In [51]:
county_earning_division.to_csv(r'C:\Users\kaurb\OneDrive\Desktop\class Folder\Final_challenge\county_earning_division.csv', index=False)

Transforming the data

In [52]:
Occupation_df=pd.read_csv('County_occupation_division_1.csv')

In [53]:
Occupation_df.count()

county_name                                  838
state_name                                   838
population_size                              838
management_business_science_arts             838
service_occupations                          838
sales_office_occupation                      838
naturalresources_construction_maintenance    838
production_transportation_materialmoving     838
dtype: int64

In [54]:
#droping NAN file 
Occupation_df=Occupation_df.dropna()
Occupation_df.count()

county_name                                  838
state_name                                   838
population_size                              838
management_business_science_arts             838
service_occupations                          838
sales_office_occupation                      838
naturalresources_construction_maintenance    838
production_transportation_materialmoving     838
dtype: int64

In [55]:
#Deleting dupicate Rows 
Occupation_df1=Occupation_df.drop_duplicates()

In [56]:
Occupation_df1.groupby('state_name').size()

state_name
 Alabama                 21
 Alaska                   3
 Arizona                 10
 Arkansas                11
 California              40
 Colorado                12
 Connecticut              8
 Delaware                 3
 District of Columbia     1
 Florida                 41
 Georgia                 37
 Hawaii                   4
 Idaho                    6
 Illinois                23
 Indiana                 26
 Iowa                    10
 Kansas                   8
 Kentucky                13
 Louisiana               17
 Maine                    6
 Maryland                16
 Massachusetts           12
 Michigan                29
 Minnesota               14
 Mississippi             10
 Missouri                17
 Montana                  6
 Nebraska                 3
 Nevada                   2
 New Hampshire            6
 New Jersey              21
 New Mexico              10
 New York                39
 North Carolina          41
 North Dakota             4
 Ohio                    39
 Oklahoma                11
 Oregon                  15
 Pennsylvania            40
 Puerto Rico             11
 Rhode Island             4
 South Carolina          22
 South Dakota             2
 Tennessee               20
 Texas                   54
 Utah                     7
 Vermont                  1
 Virginia                30
 Washington              20
 West Virginia            7
 Wisconsin               23
 Wyoming                  2
dtype: int64

In [57]:
Occupation_df1.count()

county_name                                  838
state_name                                   838
population_size                              838
management_business_science_arts             838
service_occupations                          838
sales_office_occupation                      838
naturalresources_construction_maintenance    838
production_transportation_materialmoving     838
dtype: int64

In [58]:
age_df=pd.read_csv('County_age_division.csv')
age_df.count()

state              838
population_size    838
percent_1to9       838
percent_10to14     838
percent_15to19     838
percent_20to34     838
percent_35to44     838
percent_45to64     838
percent_65plus     838
dtype: int64

In [59]:
age_df=age_df.dropna()
age_df.count()

state              838
population_size    838
percent_1to9       838
percent_10to14     838
percent_15to19     838
percent_20to34     838
percent_35to44     838
percent_45to64     838
percent_65plus     838
dtype: int64

In [60]:
education_df=pd.read_csv('county_Education_division.csv')

In [61]:
education_df=education_df.dropna()
education_df.count()

state                                                 827
population_size                                       827
percent_25year_above_high_school                      827
percent_25year_above_profeesional/assicate_diploma    827
percent_25year_above_bachelors_degree                 827
percent_25year_above_bacholors and above              827
dtype: int64

In [62]:
earning_df=pd.read_csv('county_earning_division.csv')

In [63]:
earning_df=earning_df.dropna()
earning_df.count()

index                                 838
state                                 838
population_size                       838
Median_household_income               838
Median_houshold_year_round_incomes    838
dtype: int64

Loading to the Sql

In [64]:
from sqlalchemy import create_engine
import psycopg2

In [65]:
from config import db_password

ImportError: cannot import name 'db_password'

In [66]:
db_string = f"postgres://postgres:XXXXXXX@127.0.0.1:5432/Census_data"

In [67]:
engine = create_engine(db_string)

In [69]:
education_df.to_sql(name='education_v6', con=engine)

In [70]:
age_df.to_sql(name='age_v6', con=engine)

In [71]:
Occupation_df1.to_sql(name='occupation_v6', con=engine)

In [72]:
earning_df.to_sql(name='earning_v6', con=engine)

In [73]:
#DP02_0015E
#County family Level 
county_avg_householdsize_division = censusdata.download('acs1', 2018, censusdata.censusgeo([('county', '*')]),
                                   ['DP02_0016E'],
                                   tabletype='profile')
county_avg_householdsize_division .head(10)

                                                    DP02_0016E
Morgan County, Alabama: Summary level: 050, sta...        3.11
Kings County, California: Summary level: 050, s...        3.53
Monterey County, California: Summary level: 050...        3.87
Nevada County, California: Summary level: 050, ...        2.88
Shasta County, California: Summary level: 050, ...        3.04
Yuba County, California: Summary level: 050, st...        3.47
Douglas County, Colorado: Summary level: 050, s...        3.13
Fairfield County, Connecticut: Summary level: 0...        3.24
Kent County, Delaware: Summary level: 050, stat...        3.10
New Castle County, Delaware: Summary level: 050...        3.32

In [74]:
county_avg_householdsize_division =county_avg_householdsize_division.rename(columns={'DP02_0016E': 'Average_house_hold_size'})

In [75]:
county_avg_householdsize_division.head(10)

                                                    Average_house_hold_size
Morgan County, Alabama: Summary level: 050, sta...                     3.11
Kings County, California: Summary level: 050, s...                     3.53
Monterey County, California: Summary level: 050...                     3.87
Nevada County, California: Summary level: 050, ...                     2.88
Shasta County, California: Summary level: 050, ...                     3.04
Yuba County, California: Summary level: 050, st...                     3.47
Douglas County, Colorado: Summary level: 050, s...                     3.13
Fairfield County, Connecticut: Summary level: 0...                     3.24
Kent County, Delaware: Summary level: 050, stat...                     3.10
New Castle County, Delaware: Summary level: 050...                     3.32

In [76]:
county_median_age_division = censusdata.download('acs1', 2018, censusdata.censusgeo([('county', '*')]),
                                   ['DP05_0018E'],
                                   tabletype='profile')
county_median_age_division.head(10)

                                                    DP05_0018E
Morgan County, Alabama: Summary level: 050, sta...        40.7
Kings County, California: Summary level: 050, s...        32.0
Monterey County, California: Summary level: 050...        34.7
Nevada County, California: Summary level: 050, ...        50.5
Shasta County, California: Summary level: 050, ...        41.5
Yuba County, California: Summary level: 050, st...        33.8
Douglas County, Colorado: Summary level: 050, s...        39.1
Fairfield County, Connecticut: Summary level: 0...        40.8
Kent County, Delaware: Summary level: 050, stat...        38.1
New Castle County, Delaware: Summary level: 050...        38.4

In [77]:
county_median_age_division =county_median_age_division .rename(columns={'DP05_0018E': 'Median_age'})

In [78]:
county_median_age_division.head(10)

                                                    Median_age
Morgan County, Alabama: Summary level: 050, sta...        40.7
Kings County, California: Summary level: 050, s...        32.0
Monterey County, California: Summary level: 050...        34.7
Nevada County, California: Summary level: 050, ...        50.5
Shasta County, California: Summary level: 050, ...        41.5
Yuba County, California: Summary level: 050, st...        33.8
Douglas County, Colorado: Summary level: 050, s...        39.1
Fairfield County, Connecticut: Summary level: 0...        40.8
Kent County, Delaware: Summary level: 050, stat...        38.1
New Castle County, Delaware: Summary level: 050...        38.4

In [79]:
#Resetting  the index 
county_median_age_division.reset_index(level=0, inplace=True)
county_avg_householdsize_division.reset_index(level=0, inplace=True)

In [80]:
county_avg_householdsize_division.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 838 entries, 0 to 837
Data columns (total 2 columns):
index                      838 non-null object
Average_house_hold_size    827 non-null float64
dtypes: float64(1), object(1)
memory usage: 13.2+ KB

In [81]:
county_avg_householdsize_division.to_csv(r'C:\Users\kaurb\OneDrive\Desktop\class Folder\Final_challenge\county_avg_householdsize_division.csv', index=False)

In [82]:
county_median_age_division.to_csv(r'C:\Users\kaurb\OneDrive\Desktop\class Folder\Final_challenge\county_median_age_division.csv', index=False)

In [83]:
Media_age_df=pd.read_csv('county_median_age_division.csv')

In [84]:
family_size_df=pd.read_csv('county_avg_householdsize_division.csv')

In [85]:
Media_age_df.head(10)

                                               index  Median_age
0  Morgan County, Alabama: Summary level: 050, st...        40.7
1  Kings County, California: Summary level: 050, ...        32.0
2  Monterey County, California: Summary level: 05...        34.7
3  Nevada County, California: Summary level: 050,...        50.5
4  Shasta County, California: Summary level: 050,...        41.5
5  Yuba County, California: Summary level: 050, s...        33.8
6  Douglas County, Colorado: Summary level: 050, ...        39.1
7  Fairfield County, Connecticut: Summary level: ...        40.8
8  Kent County, Delaware: Summary level: 050, sta...        38.1
9  New Castle County, Delaware: Summary level: 05...        38.4

In [86]:
family_size_df.head()

                                               index  Average_house_hold_size
0  Morgan County, Alabama: Summary level: 050, st...                     3.11
1  Kings County, California: Summary level: 050, ...                     3.53
2  Monterey County, California: Summary level: 05...                     3.87
3  Nevada County, California: Summary level: 050,...                     2.88
4  Shasta County, California: Summary level: 050,...                     3.04

In [87]:
family_size_df.to_sql(name='family_size_v1', con=engine)

In [88]:
Media_age_df.to_sql(name='median_age_v2', con=engine)